var nurseDropdowns = {
    "specialty": [
        { "speciality_id":"1", "Name":"Generalist" },
        { "speciality_id":"1", "Name":"Psychiatric" },
        { "speciality_id":"1", "Name":"Home health" },
        { "speciality_id":"1", "Name":"School" },
        { "speciality_id":"1", "Name":"Neurotrauma" }
    ],
    "experience" : [
        { "yrs_xp_id":"1", "yrs_xp":"less than 5"},
        { "yrs_xp_id":"2", "yrs_xp":"5-10"},
        { "yrs_xp_id":"3", "yrs_xp":"10-15"},
        { "yrs_xp_id":"4", "yrs_xp":"15+"}
    ]
};


var nurseData = {
    "cols": [
        "user_id ",
        "display_nm",
        "location",
        "rn_certnum",
        "yrs_xp",
        "specialty ",
        "bio",
        "resume ",
        "image ",
        "ph_num",
        "email",
        "rating",
        "hr_rate ",
        "availability ",
        "header "
    ],
    "data": [
        [
            1,
            "Brady Figueroa",
            "-39.35719, 80.43019",
            "36206313",
            15,
            "PSYCHIATRIC",
            "quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec",
            "sem, vitae aliquam",
            "augue ut lacus.",
            "1-255-911-1226",
            "urna.Nullam.lobortis@malesuadavel.net",
            2,
            26,
            0,
            "molestie tellus. Aenean egestas hendrerit"
        ],
        [
            2,
            "Gisela Thornton",
            "-40.98998, 49.46531",
            "35734938",
            9,
            "NEUROTRAUMA",
            "augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui",
            "diam. Duis mi",
            "eu tellus. Phasellus",
            "1-463-941-8741",
            "Proin@est.net",
            5,
            27,
            0,
            "diam at pretium aliquet, metus"
        ],
        [
            3,
            "Mira Patel",
            "-81.60602, 117.35318",
            "13985049",
            4,
            "SCHOOL",
            "Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit,",
            "arcu. Vivamus sit",
            "at augue id",
            "1-360-574-4150",
            "non@egestasFusce.org",
            1,
            40,
            0,
            "Donec sollicitudin adipiscing ligula. Aenean"
        ],
        [
            4,
            "Cameron Ortiz",
            "59.1288, 31.27488",
            "26487505",
            16,
            "HOME HEALTH",
            "odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor",
            "sapien. Nunc pulvinar",
            "tellus eu augue",
            "1-638-295-9281",
            "sociis.natoque.penatibus@Sedeunibh.co.uk",
            3,
            31,
            1,
            "adipiscing elit. Curabitur sed tortor."
        ],
        [
            5,
            "Porter Gilbert",
            "-57.16523, 16.70759",
            "37154453",
            4,
            "HOME HEALTH",
            "eu tellus. Phasellus elit pede, malesuada vel, venenatis",
            "nascetur ridiculus mus.",
            "Morbi quis urna.",
            "1-979-414-6551",
            "lobortis@In.ca",
            5,
            55,
            1,
            "lobortis augue scelerisque mollis. Phasellus"
        ],
        [
            6,
            "Joseph Nielsen",
            "81.96277, 25.8645",
            "33946218",
            20,
            "GENERALIST",
            "non arcu. Vivamus",
            "dapibus quam quis",
            "id enim. Curabitur",
            "1-950-947-8865",
            "vel.quam@fermentumvelmauris.ca",
            3,
            41,
            0,
            "Aliquam ornare, libero at auctor"
        ],
        [
            7,
            "Eagan Wyatt",
            "-84.98317, 55.98289",
            "47697714",
            19,
            "NEUROTRAUMA",
            "pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi.",
            "vitae semper egestas,",
            "In mi pede,",
            "1-709-141-6108",
            "Etiam.laoreet.libero@vitae.net",
            4,
            49,
            1,
            "natoque penatibus et magnis dis"
        ],
        [
            8,
            "Tanya Lawrence",
            "-24.78076, -99.58631",
            "19510846",
            13,
            "HOME HEALTH",
            "tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc",
            "varius ultrices, mauris",
            "ac nulla. In",
            "1-833-700-5640",
            "magnis.dis.parturient@imperdiet.ca",
            2,
            46,
            0,
            "magna. Suspendisse tristique neque venenatis"
        ],
        [
            9,
            "Liberty Elliott",
            "36.867, -28.63334",
            "43697420",
            16,
            "HOME HEALTH",
            "sapien molestie orci tincidunt",
            "auctor. Mauris vel",
            "ante. Vivamus non",
            "1-268-716-9413",
            "tempor@cursus.edu",
            5,
            50,
            1,
            "Phasellus in felis. Nulla tempor"
        ],
        [
            10,
            "Lenore Thompson",
            "46.5361, 2.21963",
            "24347975",
            18,
            "HOME HEALTH",
            "tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien",
            "imperdiet ornare. In",
            "mollis dui, in",
            "1-484-745-2687",
            "purus@iaculisaliquetdiam.edu",
            3,
            54,
            0,
            "iaculis nec, eleifend non, dapibus"
        ],
        [
            11,
            "Nevada Mcintyre",
            "53.44114, -162.82298",
            "14005407",
            1,
            "SCHOOL",
            "auctor non, feugiat",
            "interdum ligula eu",
            "quis, pede. Suspendisse",
            "1-730-228-1695",
            "blandit.Nam@egetipsum.org",
            4,
            53,
            1,
            "egestas a, scelerisque sed, sapien."
        ],
        [
            12,
            "Brenden Ruiz",
            "-87.50464, -176.85047",
            "43822079",
            5,
            "SCHOOL",
            "sit amet, dapibus id, blandit at, nisi.",
            "at lacus. Quisque",
            "eu erat semper",
            "1-169-646-8824",
            "mollis@amagna.ca",
            5,
            56,
            1,
            "Phasellus ornare. Fusce mollis. Duis"
        ],
        [
            13,
            "Claudia Frost",
            "71.22364, 30.82248",
            "23413547",
            4,
            "GENERALIST",
            "nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel",
            "Aenean euismod mauris",
            "semper, dui lectus",
            "1-262-866-8403",
            "fringilla@egestas.com",
            1,
            46,
            0,
            "auctor. Mauris vel turpis. Aliquam"
        ],
        [
            14,
            "Jessamine Sosa",
            "-40.02929, 163.33272",
            "25163928",
            6,
            "HOME HEALTH",
            "id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non",
            "odio a purus.",
            "blandit viverra. Donec",
            "1-712-769-8951",
            "Nunc@interdumNuncsollicitudin.edu",
            1,
            35,
            1,
            "lorem, eget mollis lectus pede"
        ],
        [
            15,
            "Maia Moran",
            "-72.69878, -104.37781",
            "11568286",
            5,
            "SCHOOL",
            "varius et, euismod et, commodo at, libero. Morbi",
            "fringilla cursus purus.",
            "Nulla eget metus",
            "1-473-830-6795",
            "pretium.aliquet.metus@Donec.com",
            4,
            48,
            0,
            "rutrum, justo. Praesent luctus. Curabitur"
        ],
        [
            16,
            "Kimberly Browning",
            "-28.02633, 142.8681",
            "44162917",
            13,
            "NEUROTRAUMA",
            "pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus,",
            "lorem, luctus ut,",
            "elit. Etiam laoreet,",
            "1-974-691-1293",
            "ante.dictum@seddictum.ca",
            1,
            25,
            1,
            "lobortis quis, pede. Suspendisse dui."
        ],
        [
            17,
            "Lev Page",
            "-76.10747, 160.46185",
            "31596254",
            13,
            "GENERALIST",
            "posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora",
            "orci. Ut sagittis",
            "montes, nascetur ridiculus",
            "1-745-224-4210",
            "Vivamus.nisi@primisinfaucibus.co.uk",
            2,
            44,
            0,
            "eros non enim commodo hendrerit."
        ],
        [
            18,
            "Amy Osborn",
            "-71.97933, -29.02584",
            "17366459",
            19,
            "NEUROTRAUMA",
            "parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim.",
            "urna. Nullam lobortis",
            "accumsan convallis, ante",
            "1-261-709-9731",
            "tempus.mauris@nostraperinceptos.ca",
            3,
            56,
            1,
            "nibh. Quisque nonummy ipsum non"
        ],
        [
            19,
            "Alexandra Schneider",
            "17.13917, 161.08424",
            "43442573",
            9,
            "SCHOOL",
            "id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis",
            "purus gravida sagittis.",
            "quis, pede. Praesent",
            "1-409-353-2096",
            "non@orci.co.uk",
            1,
            44,
            1,
            "eu, euismod ac, fermentum vel,"
        ],
        [
            20,
            "India Simmons",
            "31.92375, -170.54815",
            "42527988",
            13,
            "SCHOOL",
            "Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere,",
            "ac mattis semper,",
            "laoreet lectus quis",
            "1-922-435-2643",
            "ac.libero@antedictumcursus.com",
            3,
            51,
            0,
            "Maecenas iaculis aliquet diam. Sed"
        ],
        [
            21,
            "Thor Cline",
            "-80.12192, -78.90167",
            "30842286",
            12,
            "PSYCHIATRIC",
            "magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue",
            "facilisis eget, ipsum.",
            "porttitor interdum. Sed",
            "1-705-530-5079",
            "ornare@nisi.com",
            4,
            39,
            1,
            "semper et, lacinia vitae, sodales"
        ],
        [
            22,
            "Zeph Conway",
            "-67.21244, -108.91556",
            "49177438",
            7,
            "HOME HEALTH",
            "malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,",
            "Duis a mi",
            "ante ipsum primis",
            "1-486-744-0411",
            "Fusce.mi@ornareFusce.co.uk",
            4,
            37,
            1,
            "justo nec ante. Maecenas mi"
        ],
        [
            23,
            "Reuben Bond",
            "-34.56415, -178.83279",
            "22502486",
            6,
            "SCHOOL",
            "luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi",
            "Duis elementum, dui",
            "magna. Ut tincidunt",
            "1-406-977-1576",
            "magna.et@interdum.co.uk",
            2,
            30,
            0,
            "tellus. Suspendisse sed dolor. Fusce"
        ],
        [
            24,
            "Jason Brady",
            "-16.38531, 0.55015",
            "38336782",
            16,
            "GENERALIST",
            "quis,",
            "nisl. Nulla eu",
            "posuere at, velit.",
            "1-330-227-5622",
            "Donec.tempor@elita.net",
            5,
            40,
            0,
            "Sed diam lorem, auctor quis,"
        ],
        [
            25,
            "Dana Padilla",
            "-69.1707, 101.5514",
            "9722047",
            20,
            "HOME HEALTH",
            "eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam",
            "ligula consectetuer rhoncus.",
            "ligula elit, pretium",
            "1-118-910-7543",
            "ornare.lectus.justo@Maecenas.edu",
            5,
            36,
            1,
            "netus et malesuada fames ac"
        ],
        [
            26,
            "Skyler Matthews",
            "86.01445, 20.05538",
            "14312947",
            17,
            "HOME HEALTH",
            "sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam",
            "Morbi neque tellus,",
            "ut, pharetra sed,",
            "1-450-827-5049",
            "ultrices.posuere@a.edu",
            1,
            44,
            1,
            "non, dapibus rutrum, justo. Praesent"
        ],
        [
            27,
            "Lee Saunders",
            "54.46951, 27.0789",
            "24925315",
            20,
            "GENERALIST",
            "Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere",
            "in lobortis tellus",
            "ligula eu enim.",
            "1-298-267-1039",
            "ipsum.nunc.id@maurisrhoncusid.co.uk",
            4,
            28,
            1,
            "nisi. Mauris nulla. Integer urna."
        ],
        [
            28,
            "Sharon Gallagher",
            "80.73309, -53.40187",
            "49470460",
            19,
            "SCHOOL",
            "fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et",
            "Nullam scelerisque neque",
            "fermentum metus. Aenean",
            "1-779-167-2157",
            "non.lobortis.quis@Nullam.net",
            2,
            40,
            1,
            "In condimentum. Donec at arcu."
        ],
        [
            29,
            "Zena Acevedo",
            "55.6205, 16.98854",
            "36662028",
            6,
            "GENERALIST",
            "fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit.",
            "ipsum. Suspendisse non",
            "placerat velit. Quisque",
            "1-977-935-0835",
            "faucibus@eget.net",
            2,
            42,
            1,
            "arcu et pede. Nunc sed"
        ],
        [
            30,
            "Neve Holmes",
            "60.29838, -22.3451",
            "37934937",
            9,
            "GENERALIST",
            "rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue",
            "interdum libero dui",
            "mattis. Cras eget",
            "1-772-544-1465",
            "orci@Infaucibus.edu",
            1,
            45,
            0,
            "Suspendisse sagittis. Nullam vitae diam."
        ],
        [
            31,
            "Linus Holt",
            "-0.87165, -2.85393",
            "29269965",
            12,
            "HOME HEALTH",
            "ac orci. Ut semper pretium neque. Morbi",
            "mauris sit amet",
            "amet nulla. Donec",
            "1-152-945-1133",
            "nec@auctor.edu",
            2,
            28,
            1,
            "mollis. Integer tincidunt aliquam arcu."
        ],
        [
            32,
            "Vaughan Hernandez",
            "-88.80342, 38.57503",
            "19195279",
            20,
            "SCHOOL",
            "ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem",
            "at pretium aliquet,",
            "magna nec quam.",
            "1-986-184-2835",
            "ante.bibendum.ullamcorper@aliquet.org",
            1,
            44,
            1,
            "Proin velit. Sed malesuada augue"
        ],
        [
            33,
            "Lenore Castro",
            "-78.98848, -92.35456",
            "43882740",
            3,
            "PSYCHIATRIC",
            "adipiscing fringilla, porttitor vulputate,",
            "lacus, varius et,",
            "a, auctor non,",
            "1-910-356-0744",
            "porttitor@eros.com",
            2,
            35,
            1,
            "nec enim. Nunc ut erat."
        ],
        [
            34,
            "Zena Cherry",
            "-71.86693, -148.19517",
            "48912812",
            13,
            "SCHOOL",
            "molestie arcu. Sed eu nibh vulputate mauris sagittis",
            "euismod urna. Nullam",
            "luctus felis purus",
            "1-250-797-5956",
            "ut.erat@nonarcu.com",
            5,
            50,
            0,
            "ac tellus. Suspendisse sed dolor."
        ],
        [
            35,
            "Idona Castro",
            "-46.48733, -135.28397",
            "7929355",
            2,
            "NEUROTRAUMA",
            "elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero",
            "egestas a, scelerisque",
            "interdum. Nunc sollicitudin",
            "1-936-988-5145",
            "nunc.interdum@sapiengravida.org",
            1,
            25,
            1,
            "non massa non ante bibendum"
        ],
        [
            36,
            "Harlan Ingram",
            "3.7558, -115.82597",
            "25248666",
            6,
            "GENERALIST",
            "et netus",
            "malesuada fames ac",
            "Nunc sollicitudin commodo",
            "1-653-656-3993",
            "sit.amet@Nullamenim.com",
            3,
            41,
            1,
            "risus. Donec egestas. Aliquam nec"
        ],
        [
            37,
            "Yuli Solis",
            "-30.55698, -22.38071",
            "48675238",
            12,
            "GENERALIST",
            "Phasellus",
            "Nunc sed orci",
            "sodales purus, in",
            "1-501-100-4905",
            "pharetra.sed.hendrerit@erat.co.uk",
            2,
            28,
            0,
            "mus. Aenean eget magna. Suspendisse"
        ],
        [
            38,
            "Uriah Bauer",
            "-1.03292, -94.96684",
            "45653066",
            17,
            "SCHOOL",
            "Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum",
            "tristique senectus et",
            "dis parturient montes,",
            "1-676-859-3358",
            "sed.facilisis@idenim.co.uk",
            3,
            31,
            0,
            "vitae, posuere at, velit. Cras"
        ],
        [
            39,
            "Xanthus Vincent",
            "30.27266, 63.23387",
            "50464650",
            16,
            "SCHOOL",
            "tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor",
            "semper pretium neque.",
            "eu, euismod ac,",
            "1-268-689-2883",
            "facilisis.vitae.orci@eros.net",
            3,
            44,
            0,
            "semper auctor. Mauris vel turpis."
        ],
        [
            40,
            "Jena Thornton",
            "-26.58166, -177.26635",
            "16643631",
            6,
            "GENERALIST",
            "Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.",
            "dignissim tempor arcu.",
            "ligula. Nullam enim.",
            "1-189-879-1490",
            "magna@eunibhvulputate.ca",
            5,
            25,
            1,
            "sit amet, risus. Donec nibh"
        ],
        [
            41,
            "Audrey Flynn",
            "-86.66574, 16.04079",
            "36133660",
            19,
            "NEUROTRAUMA",
            "mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque.",
            "quis diam. Pellentesque",
            "Integer tincidunt aliquam",
            "1-325-308-0825",
            "velit@sapien.com",
            3,
            40,
            0,
            "ante bibendum ullamcorper. Duis cursus,"
        ],
        [
            42,
            "Ina Nielsen",
            "-32.59193, -72.9011",
            "41069731",
            8,
            "GENERALIST",
            "at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor.",
            "Duis a mi",
            "ridiculus mus. Proin",
            "1-154-461-0892",
            "eleifend.egestas@ullamcorper.ca",
            3,
            30,
            1,
            "enim, condimentum eget, volutpat ornare,"
        ],
        [
            43,
            "Nichole Jacobs",
            "-36.22714, -154.32992",
            "34422482",
            16,
            "HOME HEALTH",
            "et, eros. Proin ultrices. Duis volutpat",
            "lobortis. Class aptent",
            "consequat enim diam",
            "1-381-668-3725",
            "Suspendisse@in.edu",
            1,
            36,
            0,
            "neque. Nullam nisl. Maecenas malesuada"
        ],
        [
            44,
            "Jasmine Payne",
            "73.13692, -91.44044",
            "38834856",
            17,
            "GENERALIST",
            "nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per",
            "dis parturient montes,",
            "libero. Integer in",
            "1-852-445-0685",
            "nunc@diamSeddiam.net",
            5,
            35,
            0,
            "quis accumsan convallis, ante lectus"
        ],
        [
            45,
            "Moana Cabrera",
            "29.26145, 81.07373",
            "14939569",
            9,
            "GENERALIST",
            "et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget",
            "non, lacinia at,",
            "libero. Proin sed",
            "1-824-351-3004",
            "Sed.molestie.Sed@dapibus.edu",
            3,
            42,
            0,
            "Vestibulum accumsan neque et nunc."
        ],
        [
            46,
            "Nevada Nguyen",
            "77.282, -147.97285",
            "45539512",
            4,
            "HOME HEALTH",
            "dui. Cras pellentesque. Sed",
            "tristique pharetra. Quisque",
            "et, rutrum non,",
            "1-137-197-9089",
            "sagittis.semper.Nam@utnullaCras.co.uk",
            3,
            47,
            0,
            "commodo hendrerit. Donec porttitor tellus"
        ],
        [
            47,
            "Rajah Allison",
            "-9.74255, -174.341",
            "42109321",
            9,
            "NEUROTRAUMA",
            "risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris",
            "erat, in consectetuer",
            "rhoncus. Nullam velit",
            "1-899-159-4121",
            "faucibus.leo@felispurus.co.uk",
            3,
            45,
            1,
            "purus. Duis elementum, dui quis"
        ],
        [
            48,
            "Leslie Rodgers",
            "44.85829, -172.72794",
            "29472897",
            6,
            "HOME HEALTH",
            "vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu.",
            "metus eu erat",
            "a nunc. In",
            "1-545-810-8882",
            "enim.non@vitae.ca",
            5,
            25,
            1,
            "semper tellus id nunc interdum"
        ],
        [
            49,
            "Lunea Stanton",
            "-20.28625, 174.90176",
            "44495964",
            19,
            "NEUROTRAUMA",
            "metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam.",
            "lacus. Quisque imperdiet,",
            "ornare placerat, orci",
            "1-518-723-2863",
            "sed@aliquet.net",
            4,
            26,
            0,
            "Nunc ac sem ut dolor"
        ],
        [
            50,
            "Cassady Witt",
            "-0.00539, -85.07377",
            "47297783",
            15,
            "PSYCHIATRIC",
            "imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis",
            "mauris sit amet",
            "lacus, varius et,",
            "1-365-440-4333",
            "scelerisque@nonummyipsumnon.edu",
            4,
            55,
            1,
            "Nullam feugiat placerat velit. Quisque"
        ],
        [
            51,
            "Carly White",
            "-13.49049, 107.25208",
            "5357748",
            16,
            "PSYCHIATRIC",
            "at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada",
            "Etiam vestibulum massa",
            "amet, consectetuer adipiscing",
            "1-355-939-4289",
            "orci.lobortis.augue@tinciduntorciquis.org",
            5,
            31,
            0,
            "Integer eu lacus. Quisque imperdiet,"
        ],
        [
            52,
            "Kenyon Townsend",
            "78.82932, 83.72506",
            "9735410",
            8,
            "PSYCHIATRIC",
            "nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel",
            "justo. Proin non",
            "neque. Nullam ut",
            "1-651-923-8879",
            "Sed@sedtortorInteger.net",
            1,
            31,
            0,
            "Curabitur ut odio vel est"
        ],
        [
            53,
            "Demetria Nichols",
            "31.01394, 93.64896",
            "7794469",
            15,
            "NEUROTRAUMA",
            "sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis",
            "Vestibulum accumsan neque",
            "in aliquet lobortis,",
            "1-587-127-7793",
            "congue.In@velitPellentesque.com",
            3,
            46,
            0,
            "neque venenatis lacus. Etiam bibendum"
        ],
        [
            54,
            "Lareina Glenn",
            "-25.86784, 96.8084",
            "14997413",
            20,
            "HOME HEALTH",
            "dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit",
            "rutrum lorem ac",
            "semper. Nam tempor",
            "1-528-479-0743",
            "amet.nulla@velitdui.org",
            2,
            52,
            1,
            "mi lorem, vehicula et, rutrum"
        ],
        [
            55,
            "Reuben Bryan",
            "71.0195, 33.89049",
            "25092568",
            7,
            "PSYCHIATRIC",
            "molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus.",
            "Aliquam erat volutpat.",
            "egestas rhoncus. Proin",
            "1-701-938-4059",
            "iaculis.lacus@ametconsectetueradipiscing.org",
            4,
            55,
            0,
            "sem ut cursus luctus, ipsum"
        ],
        [
            56,
            "Grace Nash",
            "40.95221, 35.56519",
            "24558347",
            11,
            "NEUROTRAUMA",
            "vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum",
            "sit amet ultricies",
            "sollicitudin a, malesuada",
            "1-756-972-9714",
            "eleifend.egestas.Sed@odio.net",
            4,
            37,
            0,
            "Curae; Donec tincidunt. Donec vitae"
        ],
        [
            57,
            "Inez Spears",
            "85.29357, -166.49948",
            "9593671",
            11,
            "NEUROTRAUMA",
            "facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in",
            "vitae sodales nisi",
            "ante lectus convallis",
            "1-545-487-7195",
            "dis.parturient@adipiscing.org",
            5,
            41,
            0,
            "aliquet vel, vulputate eu, odio."
        ],
        [
            58,
            "Jenna Gregory",
            "55.7448, 165.79787",
            "11852438",
            16,
            "GENERALIST",
            "tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque",
            "Duis at lacus.",
            "sodales elit erat",
            "1-822-639-7802",
            "metus@neque.ca",
            2,
            43,
            1,
            "ridiculus mus. Proin vel nisl."
        ],
        [
            59,
            "Haley Nguyen",
            "-6.72487, -57.24852",
            "45649298",
            19,
            "HOME HEALTH",
            "a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris",
            "Aenean sed pede",
            "arcu. Sed eu",
            "1-621-438-6289",
            "et.rutrum.non@velit.net",
            5,
            33,
            1,
            "lacinia vitae, sodales at, velit."
        ],
        [
            60,
            "Cullen Mcfarland",
            "0.49392, -62.1516",
            "16544483",
            6,
            "NEUROTRAUMA",
            "ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,",
            "a nunc. In",
            "diam nunc, ullamcorper",
            "1-640-693-4724",
            "et.libero.Proin@eu.com",
            1,
            43,
            0,
            "justo nec ante. Maecenas mi"
        ],
        [
            61,
            "Porter Ray",
            "61.30777, -24.84119",
            "41494493",
            5,
            "PSYCHIATRIC",
            "consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida.",
            "id enim. Curabitur",
            "enim. Suspendisse aliquet,",
            "1-469-556-5100",
            "Fusce.dolor.quam@interdum.com",
            5,
            33,
            1,
            "in faucibus orci luctus et"
        ],
        [
            62,
            "Chava Hudson",
            "25.41905, 158.1397",
            "23963692",
            5,
            "HOME HEALTH",
            "dapibus quam quis diam. Pellentesque habitant morbi",
            "parturient montes, nascetur",
            "lobortis mauris. Suspendisse",
            "1-327-426-9354",
            "lobortis@nisi.ca",
            1,
            38,
            1,
            "cubilia Curae; Donec tincidunt. Donec"
        ],
        [
            63,
            "Len Strickland",
            "51.39559, -131.82319",
            "6175019",
            13,
            "PSYCHIATRIC",
            "dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae",
            "lobortis mauris. Suspendisse",
            "natoque penatibus et",
            "1-384-205-9651",
            "senectus@ametluctus.ca",
            3,
            27,
            1,
            "magna. Duis dignissim tempor arcu."
        ],
        [
            64,
            "Wendy Lindsey",
            "29.26434, -54.5449",
            "33040138",
            19,
            "GENERALIST",
            "amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras",
            "odio. Nam interdum",
            "a, scelerisque sed,",
            "1-483-722-5613",
            "pretium.neque@lectuspede.ca",
            2,
            57,
            1,
            "morbi tristique senectus et netus"
        ],
        [
            65,
            "Jonas Adkins",
            "52.04171, -178.7388",
            "25965263",
            7,
            "HOME HEALTH",
            "velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque",
            "vel, convallis in,",
            "sapien, gravida non,",
            "1-770-596-2509",
            "sed@accumsanneque.org",
            5,
            51,
            0,
            "eros. Proin ultrices. Duis volutpat"
        ],
        [
            66,
            "Cynthia Waters",
            "-84.77412, -113.22766",
            "25157022",
            19,
            "SCHOOL",
            "a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce",
            "tempus mauris erat",
            "felis eget varius",
            "1-681-401-6232",
            "lacinia@ultricies.com",
            5,
            53,
            1,
            "dapibus gravida. Aliquam tincidunt, nunc"
        ],
        [
            67,
            "Owen Harding",
            "-62.60165, 69.41023",
            "35620480",
            17,
            "SCHOOL",
            "egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula",
            "scelerisque dui. Suspendisse",
            "Nulla aliquet. Proin",
            "1-115-191-2935",
            "tortor@sedorcilobortis.net",
            2,
            25,
            0,
            "lacus. Etiam bibendum fermentum metus."
        ],
        [
            68,
            "Sebastian Randall",
            "27.7819, -124.36139",
            "21567808",
            18,
            "SCHOOL",
            "convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu",
            "volutpat. Nulla facilisis.",
            "feugiat tellus lorem",
            "1-131-261-4865",
            "tempus@amet.ca",
            1,
            38,
            1,
            "dapibus quam quis diam. Pellentesque"
        ],
        [
            69,
            "Helen Bryant",
            "-51.03165, -150.57697",
            "32059575",
            12,
            "HOME HEALTH",
            "turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus",
            "magna a neque.",
            "adipiscing elit. Curabitur",
            "1-171-397-8196",
            "lorem.fringilla.ornare@nisisem.net",
            1,
            28,
            1,
            "augue malesuada malesuada. Integer id"
        ],
        [
            70,
            "Elijah Thompson",
            "-19.30954, 40.82161",
            "7345325",
            7,
            "PSYCHIATRIC",
            "vitae, sodales at, velit. Pellentesque ultricies dignissim",
            "senectus et netus",
            "aliquet. Proin velit.",
            "1-454-103-6015",
            "massa@Aliquamrutrum.co.uk",
            2,
            44,
            0,
            "vestibulum. Mauris magna. Duis dignissim"
        ],
        [
            71,
            "Kasimir Horne",
            "-22.61785, 45.234",
            "5738482",
            14,
            "PSYCHIATRIC",
            "feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla",
            "Sed eget lacus.",
            "arcu. Vivamus sit",
            "1-749-928-4803",
            "aliquet@uteros.net",
            3,
            57,
            1,
            "aliquet molestie tellus. Aenean egestas"
        ],
        [
            72,
            "Brandon Figueroa",
            "-81.02868, 41.22093",
            "30613825",
            6,
            "GENERALIST",
            "Sed nunc est, mollis non,",
            "ante bibendum ullamcorper.",
            "diam. Sed diam",
            "1-552-657-5321",
            "pede.blandit@ipsumdolor.ca",
            2,
            50,
            0,
            "Donec felis orci, adipiscing non,"
        ],
        [
            73,
            "Kuame Reyes",
            "-86.85777, -174.11825",
            "49886484",
            17,
            "HOME HEALTH",
            "magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet",
            "lorem fringilla ornare",
            "pharetra ut, pharetra",
            "1-954-693-1019",
            "montes.nascetur.ridiculus@loremvehicula.co.uk",
            1,
            46,
            1,
            "in aliquet lobortis, nisi nibh"
        ],
        [
            74,
            "Emery Mason",
            "-78.4867, -73.99032",
            "15937918",
            20,
            "SCHOOL",
            "In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi",
            "enim consequat purus.",
            "Class aptent taciti",
            "1-987-446-3932",
            "sed@atnisiCum.com",
            4,
            40,
            1,
            "pretium neque. Morbi quis urna."
        ],
        [
            75,
            "Debra Park",
            "-40.98772, 65.67764",
            "50100167",
            14,
            "GENERALIST",
            "semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus",
            "Cras dolor dolor,",
            "tincidunt orci quis",
            "1-133-719-6577",
            "augue.eu@famesac.ca",
            3,
            47,
            1,
            "mus. Aenean eget magna. Suspendisse"
        ],
        [
            76,
            "Veda Hebert",
            "-64.69102, -49.09906",
            "11780903",
            2,
            "NEUROTRAUMA",
            "nonummy ultricies",
            "mauris. Morbi non",
            "nisl elementum purus,",
            "1-269-437-7201",
            "quis.lectus@erosnon.edu",
            3,
            40,
            1,
            "nec, cursus a, enim. Suspendisse"
        ],
        [
            77,
            "Wallace Curtis",
            "-4.06097, 135.12263",
            "44475430",
            6,
            "NEUROTRAUMA",
            "sit amet,",
            "nec, malesuada ut,",
            "eget, venenatis a,",
            "1-967-950-8268",
            "sed@bibendumsed.ca",
            3,
            30,
            1,
            "quam. Pellentesque habitant morbi tristique"
        ],
        [
            78,
            "Maxwell Anthony",
            "3.90017, -64.23675",
            "12510512",
            18,
            "NEUROTRAUMA",
            "Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam",
            "sagittis semper. Nam",
            "metus vitae velit",
            "1-297-368-7892",
            "vel.convallis@congueIn.net",
            3,
            35,
            1,
            "convallis in, cursus et, eros."
        ],
        [
            79,
            "Alika Mays",
            "71.07836, -55.29458",
            "11990308",
            19,
            "HOME HEALTH",
            "consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor",
            "Donec tincidunt. Donec",
            "metus facilisis lorem",
            "1-138-842-8687",
            "lectus.Nullam.suscipit@porttitoreros.com",
            4,
            40,
            0,
            "magnis dis parturient montes, nascetur"
        ],
        [
            80,
            "Erica Bond",
            "15.91625, 77.43933",
            "21959113",
            2,
            "PSYCHIATRIC",
            "odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu.",
            "metus. Vivamus euismod",
            "sed, hendrerit a,",
            "1-724-794-8325",
            "lacinia.vitae@mattisvelit.edu",
            4,
            32,
            0,
            "In at pede. Cras vulputate"
        ],
        [
            81,
            "Dora Freeman",
            "14.21426, 172.27392",
            "10915934",
            12,
            "HOME HEALTH",
            "amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus",
            "ipsum leo elementum",
            "nunc ac mattis",
            "1-893-920-1392",
            "tellus@nonummyultriciesornare.com",
            2,
            50,
            1,
            "lacus. Ut nec urna et"
        ],
        [
            82,
            "Lars Wall",
            "-46.72721, 164.99756",
            "8659912",
            4,
            "GENERALIST",
            "nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum",
            "augue scelerisque mollis.",
            "vitae sodales nisi",
            "1-896-262-3771",
            "quis.pede.Suspendisse@SuspendisseduiFusce.net",
            1,
            28,
            0,
            "dictum cursus. Nunc mauris elit,"
        ],
        [
            83,
            "Warren Perez",
            "-55.13175, -59.33679",
            "5676453",
            13,
            "GENERALIST",
            "semper pretium neque. Morbi",
            "egestas rhoncus. Proin",
            "lacus. Cras interdum.",
            "1-328-546-6265",
            "Nunc.sed@porttitorerosnec.net",
            1,
            55,
            1,
            "magnis dis parturient montes, nascetur"
        ],
        [
            84,
            "Herman Gates",
            "44.63787, 93.8261",
            "18273518",
            6,
            "SCHOOL",
            "Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam",
            "eu elit. Nulla",
            "Nullam lobortis quam",
            "1-251-955-1301",
            "non.enim.commodo@augue.org",
            1,
            48,
            0,
            "dictum eu, eleifend nec, malesuada"
        ],
        [
            85,
            "Cruz Pruitt",
            "36.19457, 153.65318",
            "19403036",
            12,
            "PSYCHIATRIC",
            "est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend",
            "facilisis vitae, orci.",
            "neque pellentesque massa",
            "1-691-555-1166",
            "Nullam.enim@urnaetarcu.net",
            5,
            52,
            0,
            "pede blandit congue. In scelerisque"
        ],
        [
            86,
            "Karleigh Olson",
            "-46.51736, -9.16914",
            "19537144",
            12,
            "GENERALIST",
            "imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in",
            "at lacus. Quisque",
            "iaculis, lacus pede",
            "1-554-375-9828",
            "urna@velitCras.co.uk",
            1,
            57,
            1,
            "Proin sed turpis nec mauris"
        ],
        [
            87,
            "Steel Williamson",
            "-15.13134, -82.38381",
            "42421112",
            12,
            "PSYCHIATRIC",
            "sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis",
            "ullamcorper magna. Sed",
            "vitae, aliquet nec,",
            "1-316-935-2176",
            "Maecenas.iaculis@condimentumDonecat.net",
            3,
            43,
            0,
            "et, eros. Proin ultrices. Duis"
        ],
        [
            88,
            "Colin Waller",
            "-50.6871, -96.61838",
            "31326182",
            1,
            "NEUROTRAUMA",
            "sit amet lorem semper auctor. Mauris vel turpis. Aliquam",
            "tempus risus. Donec",
            "fringilla est. Mauris",
            "1-906-907-4242",
            "felis.purus.ac@acmetus.ca",
            2,
            53,
            1,
            "aliquet odio. Etiam ligula tortor,"
        ],
        [
            89,
            "Adrienne Mosley",
            "83.8832, -60.17072",
            "36592112",
            18,
            "SCHOOL",
            "bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at,",
            "elementum sem, vitae",
            "eget laoreet posuere,",
            "1-982-557-8620",
            "sed@sollicitudina.org",
            2,
            32,
            0,
            "magnis dis parturient montes, nascetur"
        ],
        [
            90,
            "Amelia Washington",
            "-31.01953, 174.27422",
            "45567042",
            12,
            "HOME HEALTH",
            "enim diam vel",
            "mollis lectus pede",
            "Etiam vestibulum massa",
            "1-522-646-7762",
            "turpis.nec.mauris@fringillacursuspurus.ca",
            4,
            56,
            1,
            "luctus. Curabitur egestas nunc sed"
        ],
        [
            91,
            "Morgan Morgan",
            "11.33637, -32.68446",
            "31797757",
            7,
            "PSYCHIATRIC",
            "lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis",
            "malesuada fames ac",
            "mauris a nunc.",
            "1-822-388-5617",
            "nisi.Mauris.nulla@enimconsequatpurus.net",
            5,
            29,
            0,
            "commodo tincidunt nibh. Phasellus nulla."
        ],
        [
            92,
            "Palmer Fowler",
            "-49.09811, -165.58304",
            "5116843",
            3,
            "GENERALIST",
            "iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam",
            "ligula consectetuer rhoncus.",
            "venenatis a, magna.",
            "1-665-463-3372",
            "Lorem.ipsum@nullaDonecnon.net",
            2,
            34,
            1,
            "blandit mattis. Cras eget nisi"
        ],
        [
            93,
            "Jessica Horton",
            "-40.38999, 35.31697",
            "48946500",
            20,
            "SCHOOL",
            "fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla",
            "hymenaeos. Mauris ut",
            "id, ante. Nunc",
            "1-156-261-2897",
            "et.magnis@sagittis.co.uk",
            3,
            48,
            0,
            "egestas rhoncus. Proin nisl sem,"
        ],
        [
            94,
            "Driscoll Page",
            "25.78102, -37.68916",
            "30349282",
            7,
            "HOME HEALTH",
            "lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo",
            "eleifend. Cras sed",
            "pharetra ut, pharetra",
            "1-405-222-3527",
            "ornare.lectus@diamProin.co.uk",
            5,
            43,
            0,
            "leo. Morbi neque tellus, imperdiet"
        ],
        [
            95,
            "Jeremy Ashley",
            "75.72601, -154.01414",
            "15385722",
            16,
            "NEUROTRAUMA",
            "sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis",
            "interdum enim non",
            "non, cursus non,",
            "1-688-217-8724",
            "convallis@convallisin.co.uk",
            2,
            51,
            0,
            "elit pede, malesuada vel, venenatis"
        ],
        [
            96,
            "Azalia Blackburn",
            "25.08951, 91.38721",
            "5190551",
            6,
            "SCHOOL",
            "amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem",
            "Suspendisse ac metus",
            "Duis sit amet",
            "1-197-426-4632",
            "eget.dictum.placerat@ipsumsodales.co.uk",
            5,
            26,
            0,
            "varius et, euismod et, commodo"
        ],
        [
            97,
            "Leah Norman",
            "-26.58013, 163.63284",
            "16098452",
            2,
            "SCHOOL",
            "quam a felis",
            "Sed eu nibh",
            "urna. Nullam lobortis",
            "1-456-343-2140",
            "et.magnis@Suspendissetristiqueneque.edu",
            2,
            51,
            0,
            "enim nec tempus scelerisque, lorem"
        ],
        [
            98,
            "Ashely Buckner",
            "57.80701, 114.81969",
            "16707876",
            20,
            "HOME HEALTH",
            "Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra",
            "arcu. Vestibulum ut",
            "porttitor eros nec",
            "1-628-551-2009",
            "posuere.vulputate@pede.ca",
            5,
            55,
            1,
            "ipsum leo elementum sem, vitae"
        ],
        [
            99,
            "Iliana Yates",
            "43.57169, -15.69224",
            "14447963",
            9,
            "PSYCHIATRIC",
            "consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis",
            "mauris blandit mattis.",
            "quis, tristique ac,",
            "1-368-407-5546",
            "nec.cursus.a@nequepellentesque.co.uk",
            3,
            25,
            1,
            "sed dui. Fusce aliquam, enim"
        ],
        [
            100,
            "Destiny Obrien",
            "-3.43106, 17.39359",
            "47620013",
            9,
            "HOME HEALTH",
            "tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent",
            "ac, fermentum vel,",
            "Lorem ipsum dolor",
            "1-705-459-5291",
            "a@ligula.co.uk",
            1,
            34,
            1,
            "commodo auctor velit. Aliquam nisl."
        ]
    ]
    
};